### ISSUE TITLE
Mystic Resurrect

### ISSUE THREAD

**Issue by klime11** [pinkipi/skill-prediction#100]
Hi, this problem is related to noctenium. When use normal "Noctenium Infusion" or "Rare Noctenium Elixir"   this skill works very fast but when I use it "Superior Noctenium elixir" skill is slow, maybe 2x slower than normal.

**Comment by pinkipi** [comment]
The list of noctenium buffs was incomplete. This should be fixed in https://github.com/pinkipi/skill-prediction/commit/ced49e67570a5b8dcb7032298db15feeca7d28cc - Thanks for bringing it to my attention.
