### ISSUE TITLE
Cross Parry Block Delay

### ISSUE THREAD

**Issue by cjfadjilani** [pinkipi/skill-prediction#13]
Cross parry animation 0ms is excellently fast while Blocking attack effect is delay for a few ms. Therefore attacks and damage goes through even though animation is up fast. I haven't checked other classes with block skills.

**Comment by pinkipi** [comment]
This is unfortunately something that cannot be fixed with mods. The server has no history buffer or boss animation queue, so you will need to take your full ping into account while blocking/iframing attacks.
