### ISSUE TITLE
Sorcerer Arcane Pulse

### ISSUE THREAD

**Issue by clem193** [pinkipi/skill-prediction#16]
Hi,

Usualy to not lose time, I start pressing Arcane Pulse during previous skill animation (so once it's done, AP start charging instantly).
But now, when I do that, most of the time once the previous skill is done, AP don't strat charging afterward (nothing happen as if I was pressing nothing).
I usualy "chain" it with Meteor or Lightning.
Sometime it does work, but mostly it don't, and it never worked during Mana Boost.

So, I have to wait previous skill is 100% done until I can start pressing AP, with is obviously shit xD (you lose a lot of time doing that, and if I press to early I lose even more cuz nothing happend ;_;)

I bet it's because AP is not simulated client-side, where others skills are (so there is some kind of conflict I guess ?)

Any idea to fix this ? ^^

**Comment by pinkipi** [comment]
Currently non-emulated skills are not retried, so even slight jitter can cause them to fail when queued. Will most likely be fixed when those skills are added, rather than supporting settings for non-emulated skills.

**Comment by clem193** [comment]
Ok, I'm looking forward to the addition of Arcane Pulse in the list then ! :)
(I'll just disable it when I play sorc until then ^^)
Ty for the fast answer

**Comment by RandomSharky** [comment]
I have the same problems. Plus when I cast hailstorm, I get the animation but the skill won't work and won't be on cooldown. I have sometimes the same problem with lightning strike. Getting the animation but not the dmg or the cooldown.

**Comment by mattsubal** [comment]
how do I install Skill-prediction or in which directory to put those files to work. ty

**Comment by clem193** [comment]
With last update, it's fixed (even if there is no AP in the skill.js ^^)
I Guess it's thanks to "Support basic charging, timed press-and-hold and chain-on-release skills"

I close it.
