### ISSUE TITLE
double grim strike animation without cooldown reset glyph

### ISSUE THREAD

**Issue by pokeboi** [pinkipi/skill-prediction#18]
i would reallly love for this to be fixed

what happens is that the grim strike animation will be casted again even if the skill is not reset.
this really slows down the pvp combo towards sundering strike by alot when using spacebar to spam it and this only happens with the  proxy on.

Thanks alot for this script and if there's a way to reach out to you in game for a small gold donation do let me know!

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
