### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by mattsubal** [pinkipi/skill-prediction#21]
I am new to this, I have recently played tera and I have ping of 200. My question is, how do I install Skill-prediction or in which directory to put those files to work. ty

**Comment by my-boy** [comment]
Extract TERA Proxy somewhere.
Extract Skill Prediction FOLDER to TERA Proxy/bin/node_modules/
(So it should look like TERA Proxy/bin/node_modules/skill-prediction-master/index.js)

Run TERA Proxy/run.bat (might need as admin)
Run TERA

**Comment by Owyn** [comment]
just a quick question, so with this you can easily play on foreign tera servers like normal and do top dps + obey boss mechanics?

**Comment by Denver3D** [comment]
Soo let's be clear about one point, This isn't a cheat or a tool helper, 

If you have 200 ping your skills are slower than someone with 50> Ping so with this you can cast some skills like if you had 50> ping even if you got normally 200 or 300  

So your dps can improve for like 30 or 40 depend on your personal skill, if it didn't then you still need to learn your class
