### ISSUE TITLE
Arcane Pulse on 1.24.0

### ISSUE THREAD

**Issue by Hoiiii** [pinkipi/skill-prediction#23]
I'm not sure if it's an issue, but the latest 1.24.0 change to Sorcerer's Arcane Pulse feels slower compared to the previous skill-prediction build. After using Arcane Pulse, I get a long animation lock before I can use Meteor. When I reverted back to the previous skill-prediction, Arcane Pulse to Meteor felt smoother and faster. Any others felt this way or just me? Thanks.

**Comment by memews** [comment]
Yes, it feels slower and i got animation locked few times also me and few friends of mine reverted to older sp before charging skills added until this fixed.

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
