### ISSUE TITLE
Thunderstrike issue, Lancer skills locked issue

### ISSUE THREAD

**Issue by my-boy** [pinkipi/skill-prediction#25]
Using version 1.24.0
Usual ping 210-240

Thunderstrike: Rarely when charging a Thunderstrike my zerker will just keep charging even after releasing the button. When I see no HP being lost I release button, block cancel, charge again and it's fine. Haven't noticed any specific thing that triggers it, just that it happened when in instance with a group. Haven't noticed it happen solo.
Edit: Also happens with Cyclone

Lancer: I've been killed then on resurrecting unable to use any skills (press buttons, nothing happens). Was able to use skills after intentionally being knocked down and using retaliate. Happened twice and I believe both times was a death from LKs second bosses rolling attack. So I was probably either knocked down when killed or in the process of falling over.

Copied from TERA Proxy cmd prompt. I think I played the zerker then the lancer. Didn't think to check immediately after issues happened sorry:

```
[SkillPrediction] S_ACTION_END: skill mismatch 6811-92-65 15-9-0 149575282 12130
3080
[SkillPrediction] S_ACTION_END: currentAction is null 6811-92-65 149575282
[SkillPrediction] S_ACTION_END: skill mismatch 6811-92-66 15-9-0 149588131 12295
4188
[SkillPrediction] S_ACTION_END: currentAction is null 6811-92-66 149588131

```

p.s.
Thank you so much for making this module. The game is so much more enjoyable now <3

**Comment by Gensoo** [comment]
Can confirm the lancer issue. Very annoying. Everything freezes, party bars grey out. Only option to restart client.
