### ISSUE TITLE
Archer Sequential Fire excessive activation

### ISSUE THREAD

**Issue by I-Need-A-Username** [pinkipi/skill-prediction#26]
Every time I try to use Sequential Fire, it seems to use it excessively. That's the only way I can think of to describe it. If I hold down the button for Final Salvo, then it can fire off up to five shots when there should only be one. It also spams me with "You cannot use that skill at the moment," whether I hold down the button or briefly tap it. However, holding the button gives me more messages.
It seems that only the last hit of these shots actually does damage and builds focus stacks, however.

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
