### ISSUE TITLE
Arcane Pulse Issue still exist I think?

### ISSUE THREAD

**Issue by Hoiiii** [pinkipi/skill-prediction#30]
First of all, thank you so much for fixing Lightning Strike because that was annoying. However I still believe Arcane Pulse -> Meteor is still slower. Before the 1.24.0 release, the transition between these two skills were very smooth than before. Is there any way to revert just the Arcane Pulse back to the older version? To the 1.23.1 build? thanks.

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
