### ISSUE TITLE
Warrior problem

### ISSUE THREAD

**Issue by Spacyx19** [pinkipi/skill-prediction#32]
I have problem with Combative Strike/Rain of Blow (Cooldown no consum and Stacks doesn't appear and Charging Slash D-Sync problem. (dash + bladedraw do nothing)

Amazing works friend!

**Comment by Resme** [comment]
Im also encountering this issue. It seems as though testing the combo without holding down a directional key mitigates the issue so i suggest trying that (i believe there's a module that deactivates directional movement keys during skill usage so perhaps you can look into that)

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
