### ISSUE TITLE
Compatibility check

### ISSUE THREAD

**Issue by Mhoz** [pinkipi/skill-prediction#46]
It keeps saying I have lockons when I don't. Also, removed 'lockons' from index.js and the same happened with fast-fire, removed both and it stopped giving me the error. 
![a585e896f68b64f60ce560d1a5be6d33](https://user-images.githubusercontent.com/27371812/28144037-9b5fe40e-673f-11e7-9e00-263d9762b34d.png)

**Comment by pinkipi** [comment]
Node.JS modules are "installed" if they're in a folder named  "node_modules" anywhere up the directory tree. If you want to keep backups of modules then either don't name the folder "node_modules" or place it somewhere else.
