### ISSUE TITLE
Ninja

### ISSUE THREAD

**Issue by FeloBear** [pinkipi/skill-prediction#54]
When I use decoy jutsu without a target, the skill goes into cooldown and does the animation

**Comment by Phyxsyus** [comment]
Did you even read the latest patchnotes?

**Comment by pinkipi** [comment]
This change was intentional by BHS (it was intended to be a "skill shot" similar to Leash), but since it degrades gameplay in unintentional ways in PvE (such as having to aim your camera upwards to hit) I've forced it to behave as it did before indefinitely. Enjoy ^^
