### ISSUE TITLE
Lancer onslaught, slayer eviscerate and measured slice, and reaper sundering strike

### ISSUE THREAD

**Issue by PotatoDesu** [pinkipi/skill-prediction#7]
The updated injector seems to have these arrows. the onslaught makes you not even move at all but it still shows for everyone else that you are. but the second you use something else as a movement they see you teleport back to square one. Slayer is if you roll and eviscerate/measured slice right away it does a phantom hit that is repeatable each time you do it and well can fast chain into anything after too and u can double over hand strike even if it doesn't reset if you do it this way. The reaper sundering strike is something that occurs ever so often where when casting sundering strike you are stuck in the animation of the finishing cast of sundering strike then it does another sundering that does nothing at all but it keeps you stuck in this animation and you are unable to move or cancel it at all. thank you for your time and look into these i guess if you can! o7

**Comment by pinkipi** [comment]
These are now fixed. Thank you.
