### ISSUE TITLE
Warrior Traverse Cut(defense stance)

### ISSUE THREAD

**Issue by DevilNocte** [pinkipi/skill-prediction#70]
Problem with animation Traverse Cut when Defensive Stance is active

**Comment by clfarron4** [comment]
Symptoms: Traverse Cut Animation Starts and then ends immediately on the first animation cast.

Offending Commit: https://github.com/pinkipi/skill-prediction/commit/c920b3bbc073b790732ceec983bd037c1e81c47d

Effects of reverting offending commit: Traverse Cut animations work as designed, but it is not possible to activate the Blade Draw chain.

This was done with the latest tera-data from meishu's tera-data.

**Comment by DevilNocte** [comment]
Updated data and skill prediction, almost nothing has changed

**Comment by pinkipi** [comment]
This is now fixed as of https://github.com/pinkipi/skill-prediction/commit/e4472373a34a5bea1bad3a7de93f18877c53bd31
