### ISSUE TITLE
the new updates wont work

### ISSUE THREAD

**Issue by fung011151** [pinkipi/skill-prediction#71]
I am still using the old skill-prediction my friend gave me. The new updates wont work for unknown reason. Everything show fine in the proxy cmd. No error occur. However, u will begin stuck when u use a skill in-game. You can infinity use ur skill without cooldown. People surround u wont notice ur move and action. In addition, you cant exit the game through the in-game system menu, can only through task manager. Thank you for help.

**Comment by pinkipi** [comment]
Update tera-proxy (or the [tera-proxy-game](https://github.com/pinkipi/tera-proxy-game) library). Old versions will go into an infinite loop upon sending any raw packet.

Currently there's no dependency version check besides packet definitions, so if something is broken it's safe to assume tera-proxy is outdated.

**Comment by fung011151** [comment]
OMG my hearts is bumping so hard. Thank you so much !
