### ISSUE TITLE
skills wont work (eu)

### ISSUE THREAD

**Issue by calibari** [pinkipi/skill-prediction#76]
hello

whenever i use skill prediction my char only uses the start animation of the skill but never uses the skill 
i can also endless spam stuff like the gunner evade roll and it never goes on cooldown :/ what am i doing wrong?

**Comment by gianpelisser** [comment]
I have same problem in my reaper, Whenever i use the skill sundering not working. Never come Cooldown.

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
