### ISSUE TITLE
Reaper's chained Sundering Strike problem

### ISSUE THREAD

**Issue by Mitamy** [pinkipi/skill-prediction#77]
If i use the sundering strike chained after grim strike, double shear, death spiral the game play the 2nd  explositon sound and shake effect two times.
Whithout chained skills works well.

**Comment by pinkipi** [comment]
Fixed in https://github.com/pinkipi/skill-prediction/commit/6ed4c5f967fd0f90816e6c795b6ecab2ee5e1cee
