### ISSUE TITLE
How to solve ERROR

### ISSUE THREAD

**Issue by a80555** [pinkipi/skill-prediction#87]
How to solve?   

ERROR tera-proxy: failed to preload module (module = skill-prediction-master)
Error: Cannot find module 'command'

**Comment by a80555** [comment]
![image](https://user-images.githubusercontent.com/34435089/33819214-4347dc60-de84-11e7-9502-1f204688c50d.png)

**Comment by russopie** [comment]
https://github.com/pinkipi/command download it and put in the same place as skill-prediction module ..\tera-proxy\bin\node_modules

**Comment by cuteelin** [comment]
![untitled](https://user-images.githubusercontent.com/39330425/40223630-00f7042c-5a84-11e8-822c-eadf793dd9ed.png)

Hello, any idea what might cause this? Everything seems to be working even after that just yeah less errors is better Im sure ;p Also I dont know if its related to this but sometimes, usually after Lancers righteous leap, my character just keeps holding block down without me doing it until I press block again.

**Comment by russopie** [comment]
seems you have to update tera-data download here https://github.com/meishuu/tera-data and extract in ...\tera-proxy\node_modules don't forget to delete the oldest and rename the new removing "-master" from the name should be somenthing like this \tera-proxy\node_modules\tera-data when you finish the process
