### ISSUE TITLE
Sorcerer's Arcane Pulse

### ISSUE THREAD

**Issue by Yulermi** [pinkipi/skill-prediction#93]
Looks like sometimes (generally on the beggining of the battle) when you full charge the Arcane pulse, the skill just fail, as a result you lose all dps and the glyph effects, It's like you've never used it before.

Please take a look on that skill for sorcerer, currently the Arcane Pulse is the first skill used on rotation and 
one of the most important.

Thank You o/

**Comment by NGSalem** [comment]
Comment it out entirely or increase the charging length in small increments, like 15 or so, until it works.

**Comment by pinkipi** [comment]
Closing this issue as it is several months old. Please open a new issue if this problem persists in the latest version.
