### ISSUE TITLE
Archer/Gunner Not Working

### ISSUE THREAD

**Issue by Rentapest** [pinkipi/skill-prediction#98]
My Valkyrie works perfectly! I love this mod!

But my Gunner and Archer do not benefit from this at all for some reason. I looked at the config, which says that the default race is Elin unless speicifed. My Gunner is Elin, and does not benefit from the reduced skill delays. However, my Archer is Human Female, and she too does not benefit.

I thought it might be that I need top configure it, but that doesn't explain why my Gunner isn't working. Skills work "ok" as they did before with the typical usual TERA lag and delays.

Please help.

**Comment by Leyki** [comment]
The script  shouldn't need any previous configuration to work from the get go, are you sure your installation has no user committed issues? Have you already tried using a fresh installation? And lastly, are you completely sure it isn't working with these classes?

**Comment by Rentapest** [comment]
Thank you for the reply Leyki.

I extracted the folder "skill-prediction-master" to the tera-proxy modules folder (Example - C:\tera-proxy\bin\node_modules\skill-prediction-master) and have not altered the files or layout at all. I have viewed some files in Wordpad, but not edited anything.

When I tested this on my Valkyrie, there was a hugely noticeable improvement in skill response times! Everything was instantaneous without any delay, it was amazing! However, my Gunner and Archer play exactly as they did before (with 1-2s delay on abilities, with me having to mash the crap out of my keyboard just to get some kind of "rotation" going on, and the worste ability is 'retaliate' which always takes so long to cast, and then the animation locks you in place). So no, I'm not certain if it's working or not, I have no idea how it should work on Gunner/Archer, but compared to how improved my Valkyrie is, I would say no this is not working for me on Gunner/Archer.

I'm just puzzled why this isn't working for my Gunner/Archer. :\

**Comment by Rentapest** [comment]
![skillprediction](https://user-images.githubusercontent.com/37276927/37372572-88e0b85c-26e9-11e8-94d7-31d9c2e8ae4b.jpg)

I'm not sure if this error is relevant or not? I launched the game without tera-proxy running and my Valkyrie is still pretty responsive, so I'm not even sure if it's working or not or just in my head!

**Comment by Rentapest** [comment]
I managed to get a newer proxy version, and it works ok. You may close this thread, thank you.
