### ISSUE TITLE
Slayer headlong rush still isn't applying the attack speed buff properly

### ISSUE THREAD

**Issue by holyinsane** [pinkipi/skill-prediction#99]
hello, this problem was looked into before, but no actual explanation nor fix has been given, so i would like to highlight this huge issue again, the as buff is not applying once the HLR is channeled towards an obstacle, from close quarters.
I believe there is some way to make the skill not to run through the module, but couldn't figure out how

**Comment by pinkipi** [comment]
Duplicate of #20
